{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.eterverda.sntp",
    "module": "sntp-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.eterverda.sntp",
          "module": "sntp",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "sntp-android-0.2.1.aar",
          "url": "sntp-android-0.2.1.aar",
          "size": 5409,
          "sha512": "c6975ea334a7764f82d0ad232a405d08cdd680a44c38edd15ce42df0febc36c366bf06752ca4e30a5c15e4687dae011c153dba735e8dffb3e512b08e435aa9e1",
          "sha256": "2b92c6fe9aab1b764c76365b00d9eec66e980064de8dfd98d20d52101a89ec1e",
          "sha1": "792423173f5d8aab1bc320993fe1d34674df95b5",
          "md5": "4e8f7ec466310a9aafe7e1cc1d5dfe7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.eterverda.sntp",
          "module": "sntp",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "sntp-android-0.2.1.aar",
          "url": "sntp-android-0.2.1.aar",
          "size": 5409,
          "sha512": "c6975ea334a7764f82d0ad232a405d08cdd680a44c38edd15ce42df0febc36c366bf06752ca4e30a5c15e4687dae011c153dba735e8dffb3e512b08e435aa9e1",
          "sha256": "2b92c6fe9aab1b764c76365b00d9eec66e980064de8dfd98d20d52101a89ec1e",
          "sha1": "792423173f5d8aab1bc320993fe1d34674df95b5",
          "md5": "4e8f7ec466310a9aafe7e1cc1d5dfe7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sntp-android-0.2.1-sources.jar",
          "url": "sntp-android-0.2.1-sources.jar",
          "size": 3979,
          "sha512": "9faed83a3eb45c2ac02bd62f7cd9be80d09f63fbf752fb9c95c0323068200f7f31c99507dfe20bdb0695d5d40a7eedd303fb4176b17d7887f7a323172a1d3911",
          "sha256": "00c07f5244e7069157e4105e5004b8149f8af98f693476bf6b714254b0d57d5b",
          "sha1": "5c8dbb6648770ba4f95e0f06d7c26e159f59dbe2",
          "md5": "b73fc00b12e4a39cd0cc83bd00f5267f"
        }
      ]
    }
  ]
}
